title: Zimaspace Docs
subtitle: "Guides and tutorials for ZimaOS, ZimaCube, ZimaBoard and ZimaBlade"
description: "Official documentation for ZimaSpace products. ZimaOS is a leading NAS operating system evolving toward an agent OS. ZimaCube is a flagship home NAS device. ZimaBoard is a hackable single board server for geeks and developers. Get setup guides, app deployment tutorials and troubleshooting help."
author: ZimaSpace
language: en
timezone: UTC

skip_render:
  - jump/*.html

include:
  - _redirects
url: https://www.zimaspace.com/docs
root: /docs
permalink: news/:year/:month/:day/:title/
archive_dir: news
default_layout: page
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: false
marked:
  prependRoot: true
  postAsset: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: zima

highlight:
  enable: true
  line_number: false
search:
  path: /search.xml
  field: all

google_analytics: GTM-WXBHPJ4N
fb_admins: 298662541343433
twitter: zimaboard


